### PR TITLE
Allow partial templates

### PR DESCRIPTION
**Pull request by Belgabor**
Simplified PR on top of the new 1.7 branch.

### CODE REVIEW

**Comment by Adubbz** [comment]
Perfect, thanks :+1:

**Comment by Belgabor** [comment]
Just wanted to add that unfortunately I later found out it doesn't work properly as soon as there are modded blocks in template dimensions, pretty sure it's because of block numerical id mappings still in 1.7.10. The terrain override stuff by @rockobonaparte achieves a similar goal with probably less issues. For our purposes I'll probably backport that to 1.7.10.

**Comment by rockobonaparte** [comment]
Well now I have to be responsible and see if Lockdown needs another PR. I made that initial commit and life was good. Then I updated some mods, and found my template came up with walls of molten bronze and other things. I had to add a bunch more code for that. It turns out that Minecraft will handle block ID migrations from saves, but it will assume a new world is using the up-to-date block ID maps. I had to add some code to force the block ID migration.

I don't think I sent it upstream because I was only testing it on 1.7.10, and I have no idea if Minecraft 1.8 or beyond even handles blocks in the same ways.

@Belgabor, that code I PR'd works pretty much as-is for 1.7.10, but I'll send a note when I have made sure my fork is updated with the block ID stuff.

I have found out since I did those changes that a few people are afraid of editing their themed packs because of the strangeness I was talking about, so I really need to share it. It's been working like a charm in Baby's First Space Race in 3 months of testing, although I haven't officially released the beta version of the pack that has all this stuff.

In truth, that block ID migration thing would probably be a problem regardless of original changes.

**Comment by Belgabor** [comment]
That would be amazing.

**Comment by rockobonaparte** [comment]
Well, it is not ready for a merge, but I got the source up:
https://github.com/rockobonaparte/Lockdown/tree/automigrate_block_ids

I am officially a horrible human being. That code is 5 months old and never went up on GitHub. Then I had to go through some shenanigans with setting aside a topic branch and merging it in, dealing with some goofy merge conflict in the process. So I suspect the mcmod.info or similar might have to be reverted, but the code in GuiCreateFixedWorld is what matters.

I had thought the fix was to explicitly migrate the blocks, but I remember now I found out I could just migrate parts of the template save's world.dat into the new world.dat, and the server would then initiate the block migration for me. This was a lot more consistent. I generally could migrate the blocks, but something would crash along the way, so I went with this gentler approach.

To be honest, I'm focused on getting a BFSR release candidate out and won't smooth out this code for a bit longer. However, at least it's now on the todo that I should get it properly PR'd back into Lockdown. I had completely forgotten I hadn't done my Good Citizenship with it already. :(

**Comment by Belgabor** [comment]
Thanks a lot =)
Not sure if that was intended, but that version still had 1.8 updates in it. I've backported that in my local copy, we'll give it a test and I'll push it if things work correctly.

**Comment by rockobonaparte** [comment]
Is all well now? I _just_ updated Baby's First Space Race over the weekend. That was an update I've been beating up on for half a year. :(

I'm trying to catch my breath!

**Pull request merged**
